import { useEffect, useRef } from "react";
import { ArrowRight, Graph, MonitorPlay, X } from "@phosphor-icons/react";

export function InteractiveExperiencePicker({ open, onClose, onDiary, onSimulation }: { open: boolean; onClose: () => void; onDiary: () => void; onSimulation: () => void }) {
  const dialog = useRef<HTMLElement>(null); const trigger = useRef<HTMLElement | null>(null);
  useEffect(() => { if (!open) return; trigger.current = document.activeElement as HTMLElement; if (typeof dialog.current?.focus === "function") dialog.current.focus(); const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); onClose(); } }; if (typeof window.addEventListener === "function") window.addEventListener("keydown", keydown); return () => { if (typeof window.removeEventListener === "function") window.removeEventListener("keydown", keydown); if (typeof trigger.current?.focus === "function") trigger.current.focus(); }; }, [onClose, open]);
  if (!open) return null;
  return <div className="experience-picker-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="experience-picker" role="dialog" aria-modal="true" aria-labelledby="experience-picker-title" ref={dialog} tabIndex={-1}><header className="experience-picker__header"><div><p>互动体验</p><h1 id="experience-picker-title">选择一个体验开始探索</h1></div><button className="experience-picker__close" type="button" onClick={onClose} aria-label="关闭互动体验选择"><X weight="bold" /></button></header><div className="experience-picker__cards"><button data-testid="choose-virus-diary" className="experience-picker__card experience-picker__card--diary" type="button" onClick={onDiary}><span className="experience-picker__icon"><MonitorPlay weight="duotone" /></span><span className="experience-picker__copy"><strong>病毒日记</strong><small>从微观视角了解人体免疫应答</small></span><span className="experience-picker__action">进入体验 <ArrowRight weight="bold" /></span></button><button data-testid="choose-virus-spreading" className="experience-picker__card experience-picker__card--spread" type="button" onClick={onSimulation}><span className="experience-picker__icon"><Graph weight="duotone" /></span><span className="experience-picker__copy"><strong>疫苗防线</strong><small>观察不同条件下的传播过程</small></span><span className="experience-picker__action">开始实验 <ArrowRight weight="bold" /></span></button></div></section></div>;
}
